import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).parent.parent
load_dotenv(BASE_DIR / ".env")

PORT = int(os.getenv("PORT", "3117"))
REFRESH_INTERVAL_MINUTES = int(os.getenv("REFRESH_INTERVAL_MINUTES", "15"))
LLM_PROVIDER = os.getenv("LLM_PROVIDER")
LLM_API_KEY = os.getenv("LLM_API_KEY")
LLM_MODEL = os.getenv("LLM_MODEL")
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL")

FRED_API_KEY = os.getenv("FRED_API_KEY")
EIA_API_KEY = os.getenv("EIA_API_KEY")
FIRMS_MAP_KEY = os.getenv("FIRMS_MAP_KEY")
ACLED_EMAIL = os.getenv("ACLED_EMAIL")
ACLED_PASSWORD = os.getenv("ACLED_PASSWORD")
AISSTREAM_API_KEY = os.getenv("AISSTREAM_API_KEY")
ADSB_API_KEY = os.getenv("ADSB_API_KEY")
REDDIT_CLIENT_ID = os.getenv("REDIIT_CLIENT_ID")
REDDIT_CLIENT_SECRET = os.getenv("REDDIT_CLIENT_SECRET")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
HACKERNEWS_API_KEY = os.getenv("HACKERNEWS_API_KEY")
BLS_API_KEY = os.getenv("BLS_API_KEY")
CLOUDFLARE_API_TOKEN = os.getenv("CLOUDFLARE_API_TOKEN")
RELIEFWEB_APPNAME = os.getenv("RELIEFWEB_APPNAME")

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
TELEGRAM_POLLING_INTERVAL = int(os.getenv("TELEGRAM_POLLING_INTERVAL", "5000"))
DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN")
DISCORD_CHANNEL_ID = os.getenv("DISCORD_CHANNEL_ID")
DISCORD_GUILD_ID = os.getenv("DISCORD_GUILD_ID")
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")
